export const GET_DISCUSSED_TIMES = 'GET_DISCUSSED_TIMES'
export const GET_OTHER_TOPICS = 'GET_OTHER_TOPICS'
export const GET_SPEAKERS_LIST = 'GET_SPEAKERS_LIST'
export const GET_TOPIC_RESULT = 'GET_TOPIC_RESULT'
